homePage: home
redirects:
  download-and-install:
    newPage: getting-started
    code: 301
  install:
    newPage: getting-started
    code: 301
  docs/hooks:
    newpage: docs/erp/advanced-development/hooks
    code: 301
  some-old-page:
    newPage: some-new-page
    code: 301
router:
tableOfContents:
  - page: home
    icon: fas fa-home
    children:
      - page: about
        # children:
        #   - page: benefits
      - page: join-us
      #   children:
      #     - page: contribute
      #       icon: fas fa-terminal
      #     - page: partnership
      #       icon: fas fa-handshake-angle
      #     - page: licenses
      #       icon: fas fa-stamp
  - page: getting-started
    icon: fas fa-download
    prev: features
    next: create-first-app
    children:
      - page: installation
      - page: nginx
  - page: cli-agent
    icon: fas fa-terminal
    children:
      - page: cli/init
  - page: apps
    icon: fas fa-bolt
    children:
      - page: apps/community
      - page: apps/enterprise
      - page: apps/external
  - page: docs
    icon: fas fa-book
    children:
      - page: docs/framework
        children:
          - page: docs/framework/routing
            children:
              - page: docs/framework/routing/defining-routes
              - page: docs/framework/routing/accessing-query-parameters
              - page: docs/framework/routing/parametric-routes
          - page: docs/framework/models
            children:
              - page: docs/framework/models/record-manager
              - page: docs/framework/models/records-api
              - page: docs/framework/models/description-api
                status: "wip"
              - page: docs/framework/models/enums-and-lookups
                status: "wip"
              - page: docs/framework/models/relations
                status: "wip"
              - page: docs/framework/models/callbacks
                status: "wip"
              - page: docs/framework/models/migrations
          - page: docs/framework/views
            children:
              - page: docs/framework/views/react-ui
          - page: docs/framework/controllers
            status: "wip"
            children:
              - page: docs/framework/controllers/html-output
                status: "wip"
              - page: docs/framework/controllers/json-output
                status: "wip"
          - page: docs/framework/ui
            status: "wip"
            children:
              - page: docs/framework/ui/creating-custom-components
                status: "wip"
              - page: docs/framework/ui/tables
                status: "wip"
              - page: docs/framework/ui/forms
                status: "wip"
              - page: docs/framework/ui/inputs
                status: "wip"
          - page: docs/framework/testing
            status: "wip"
            children:
              - page: docs/framework/testing/writing-tests
                status: "wip"
              - page: docs/framework/testing/running-tests
                status: "wip"
      - page: docs/erp
        children:
          - page: docs/erp/core
          - page: docs/erp/apps
            children:
              - page: docs/erp/apps/create-app
              - page: docs/erp/apps/folder-structure
              - page: docs/erp/apps/manifest
              - page: docs/erp/apps/loader
              - page: docs/erp/apps/routing
                status: "wip"
              - page: docs/erp/apps/models-views-controllers
                status: "wip"
              - page: docs/erp/apps/user-interface
                status: "wip"
              - page: docs/erp/apps/miscellaneous
                status: "wip"
          - page: docs/erp/conventions
          - page: docs/erp/localization
          - page: docs/erp/advanced-development
            icon: fas fa-medal
            children:
              - page: docs/erp/advanced-development/core-architecture
                children:
                  - page: docs/erp/advanced-development/core-architecture/user-management-and-authentication
              - page: docs/erp/advanced-development/dynamic-routes
              - page: docs/erp/advanced-development/data-management
                children:
                  - page: docs/erp/advanced-development/data-management/adding-custom-columns
                  - page: docs/erp/advanced-development/data-management/create-own-data-grid-table-component
              - page: docs/erp/advanced-development/customizing-ui
                children:
                  - page: docs/erp/advanced-development/customizing-ui/customizing-sidebar
                  - page: docs/erp/advanced-development/customizing-ui/view
                  - page: docs/erp/advanced-development/customizing-ui/component
                  - page: docs/erp/advanced-development/customizing-ui/forms
                  - page: docs/erp/advanced-development/customizing-ui/special-inputs
                  - page: docs/erp/advanced-development/customizing-ui/skin
                  - page: docs/erp/advanced-development/customizing-ui/material-ui
                  - page: docs/erp/advanced-development/customizing-ui/custom-invoice-templates
              - page: docs/erp/advanced-development/description-api
                children:
                  - page: docs/erp/advanced-development/description-api/table
                  - page: docs/erp/advanced-development/description-api/form
              - page: docs/erp/advanced-development/core-classes
                icon: fas fa-code
                children:
                  - page: docs/erp/advanced-development/core-classes/loader
                  - page: docs/erp/advanced-development/core-classes/model
                  - page: docs/erp/advanced-development/core-classes/eloquent
                  - page: docs/erp/advanced-development/core-classes/controller
                  - page: docs/erp/advanced-development/core-classes/router
                    status: "wip"
                  - page: docs/erp/advanced-development/core-classes/permissions
                    status: "wip"
              - page: docs/erp/advanced-development/design-patterns
                status: "wip"
                children:
                - page: docs/erp/advanced-development/crons
                - page: docs/erp/advanced-development/hooks
                  children:
                    - page: docs/erp/advanced-development/hooks/introduction
                    - page: docs/erp/advanced-development/hooks/events
                - page: docs/erp/advanced-development/pipeline
                  status: "wip"
                - page: docs/erp/advanced-development/miscellaneous/dashboard
              - page: docs/erp/advanced-development/miscellaneous
                children:
                  - page: docs/erp/advanced-development/miscellaneous/hubleto-chatgpt
  - page: source-code
    icon: fa-solid fa-code
    children:
      - page: source-code/framework/Home
      - page: source-code/erp/Home
      - page: source-code/apps
        children:
          - page: source-code/apps/Calendar/Home
          - page: source-code/apps/Campaigns/Home
          - page: source-code/apps/Contacts/Home
          - page: source-code/apps/Customers/Home
          - page: source-code/apps/Deals/Home
          - page: source-code/apps/Invoices/Home
          - page: source-code/apps/Leads/Home
          - page: source-code/apps/Orders/Home
          - page: source-code/apps/Pipeline/Home
          - page: source-code/apps/Projects/Home
          - page: source-code/apps/Settings/Home
          - page: source-code/apps/Worksheets/Home
  - page: tutorials
    icon: fa-solid fa-graduation-cap
    children:
      - page: tutorials/using-ai-to-hubleto-vibe-code
        icon: fas fa-star
        children:
      - page: tutorials/hello-world-app
        icon: fas fa-star
        children:
          - page: basics/about-apps
          - page: basics/app-folder-structure
          - page: tutorial/add-route-controller-and-view
            status: "wip"
          - page: tutorial/create-simple-addressbook
            status: "wip"
            children:
            - page: tutorial/add-model-for-contacts
              status: "wip"
            - page: tutorial/add-route-controller-and-view-for-managing-contacts
              status: "wip"
            - page: tutorial/add-1-n-relation
              status: "wip"
          - page: tutorial/customize-tables-and-forms
            status: "wip"
          - page: tutorial/custom-ui-components
            status: "wip"
          - page: tutorial/writing-tests
            status: "wip"
          - page: tutorial/more-reading
            status: "wip"
      - page: tutorials/set-up-environment-for-development
        icon: fas fa-gears
      - page: tutorials/complex-model-with-crud-components
      - page: tutorials/code-samples
      - page: tutorials/hubleto-dev-hosting
  - page: certification
    icon: fas fa-id-badge
    children:
      - page: certification/level-1
        children:
          - page: certification/level-1/webinars-dates-topics-and-links
          - page: certification/level-1/lesson-1
          - page: certification/level-1/lesson-2
          - page: certification/level-1/lesson-3
          - page: certification/level-1/lesson-4
          - page: certification/level-1/lesson-5
          - page: certification/level-1/lesson-6
          - page: certification/level-1/lesson-7
          - page: certification/level-1/lesson-8
          - page: certification/level-1/lesson-9
          - page: certification/level-1/lesson-10
      - page: certification/level-2
      - page: certification/level-3
      
